
C:\Users\tsusm\OneDrive\Desktop\skill-Projects-now\git-skill2\HibernateInventory>dir src\main\java\com\inventory\entity\
The system cannot find the file specified.

C:\Users\tsusm\OneDrive\Desktop\skill-Projects-now\git-skill2\HibernateInventory>mkdir src\main\java\com\inventory\entity

C:\Users\tsusm\OneDrive\Desktop\skill-Projects-now\git-skill2\HibernateInventory>mkdir src\main\java\com\inventory\dao

C:\Users\tsusm\OneDrive\Desktop\skill-Projects-now\git-skill2\HibernateInventory>mkdir src\main\java\com\inventory\main